### ISSUE TITLE
UnhandledError on saving extension settings

### ISSUE THREAD

**Issue by annalinneajohansson** [mikebarkmin/ulauncher-snippets#11]
Pop!_OS 21.04
GNOME Version 3.38.5

Message: 'com.github.mikebarkmin.ulauncher-snippets'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.mikebarkmin.ulauncher-snippets'

```

**Comment by mikebarkmin** [comment]
Maybe it is a missing dependency https://github.com/Ulauncher/Ulauncher/issues/354#issuecomment-473526441 . Have you installed all requirements? https://github.com/mikebarkmin/ulauncher-snippets#requirements
