### ISSUE TITLE
UnhandledError

### ISSUE THREAD

**Issue by RajDhinge** [mikebarkmin/ulauncher-snippets#2]
Message: 'com.github.mikebarkmin.ulauncher-snippets'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.9/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.9/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.mikebarkmin.ulauncher-snippets'

```

**Comment by ErebusBat** [comment]
I got a similar error and it was due to missing python packages (RTFM)

**Comment by mikebarkmin** [comment]
I have experienced the same with other plugins. It is unfortunate that one has to read the manual first. Hopefully this issue gets implemented soon. https://github.com/Ulauncher/Ulauncher/issues/273
